import { productsTable } from "@/db/schema";

type NewProduct = typeof productsTable.$inferInsert;

export const allProducts: NewProduct[] = [
    {
        name: "DevFlow",
        slug: "devflow",
        tagline: "Streamline your development workflow",
        description: "A tool to manage tasks, code reviews, and deployments in one place.",
        websiteUrl: "https://devflow.app",
        tags: ["developer", "productivity", "workflow"],
        voteCount: 120,
        status: "approved",
        submittedBy: "Tarang",
        userId: 1,
        createdAt: new Date(new Date("2024-01-01")),
        organizedId: 1,
        isFeatured: true,
    },
    {
        name: "AI Writer Pro",
        slug: "ai-writer-pro",
        tagline: "Write smarter with AI",
        description: "Generate blogs, emails, and content using advanced AI models.",
        websiteUrl: "https://aiwriterpro.com",
        tags: ["ai", "writing", "content"],
        voteCount: 85,
        status: "approved",
        submittedBy: "Rahul",
        userId: 1,
        createdAt: new Date("2024-01-01"),
        organizedId: 2,
        isFeatured: true,
    },
    {
        name: "FitTrack",
        slug: "fittrack",
        tagline: "Track your fitness journey",
        description: "Monitor workouts, calories, and progress with smart insights.",
        websiteUrl: "https://fittrack.io",
        tags: ["fitness", "health", "tracking"],
        voteCount: 45,
        status: "pending",
        submittedBy: "Ankit",
        userId: 1,
        createdAt: new Date("2024-01-01"),
        organizedId: 3,
        isFeatured: true,
    },
    {
        name: "CodeSnap",
        slug: "codesnap",
        tagline: "Beautiful code screenshots instantly",
        description: "Create and share aesthetic code snippets with ease.",
        websiteUrl: "https://codesnap.dev",
        tags: ["developer", "tools", "design"],
        voteCount: 60,
        status: "approved",
        submittedBy: "Neha",
        createdAt: new Date("2024-01-01"),
        userId: 1,
        organizedId: 2,
        isFeatured: false,
    },
    {
        name: "TaskZen",
        slug: "taskzen",
        tagline: "Minimal task management",
        description: "Stay focused with distraction-free task tracking.",
        websiteUrl: "https://taskzen.app",
        tags: ["productivity", "tasks", "minimal"],
        voteCount: 30,
        status: "pending",
        submittedBy: "Amit",
        createdAt: new Date("2024-01-01"),
        userId: 1,
        organizedId: 1,
        isFeatured: false,
    },
    {
        name: "ShopEase",
        slug: "shopease",
        tagline: "Your smart shopping assistant",
        description: "Compare prices and get the best deals instantly.",
        websiteUrl: "https://shopease.com",
        tags: ["ecommerce", "shopping", "deals"],
        voteCount: 150,
        status: "approved",
        submittedBy: "Priya",
        createdAt: new Date("2024-01-01"),
        userId: 1,
        organizedId: 4,
        isFeatured: true,
    },
    {
        name: "Learnify",
        slug: "learnify",
        tagline: "Learn anything, anytime",
        description: "An online platform for interactive learning experiences.",
        websiteUrl: "https://learnify.io",
        tags: ["education", "learning", "courses"],
        voteCount: 95,
        status: "approved",
        submittedBy: "Rohit",
        userId: 1,
        createdAt: new Date("2024-01-01"),
        organizedId: 3,
        isFeatured: true,
    },
    {
        name: "TravelMate",
        slug: "travelmate",
        tagline: "Plan trips effortlessly",
        description: "Discover destinations, plan itineraries, and book easily.",
        websiteUrl: "https://travelmate.app",
        tags: ["travel", "planning", "booking"],
        voteCount: 70,
        status: "pending",
        submittedBy: "Sneha",
        createdAt: new Date("2024-01-01"),
        userId: 1,
        organizedId: 5,
        isFeatured: false,

    },
    {
        name: "HealthSync",
        slug: "healthsync",
        tagline: "Your health, synced",
        description: "Track health data and sync across devices seamlessly.",
        websiteUrl: "https://healthsync.io",
        tags: ["health", "wellness", "tracking"],
        voteCount: 55,
        status: "rejected",
        submittedBy: "Vikas",
        createdAt: new Date("2024-01-01"),
        userId: 1,
        organizedId: 3,
        isFeatured: false,
    },
    {
        name: "PitchDeck AI",
        slug: "pitchdeck-ai",
        tagline: "Create investor-ready decks with AI",
        description: "Generate stunning startup pitch decks in minutes.",
        websiteUrl: "https://pitchdeckai.com",
        tags: ["startup", "ai", "presentation"],
        voteCount: 200,
        status: "approved",
        submittedBy: "Karan",
        createdAt: new Date("2024-01-01"),
        userId: 1,
        organizedId: 2,
        isFeatured: true,
    },
];